### PR TITLE
fs: Fix use of uninitialized value in `ZonedBlockDevice` destructor

### PR DESCRIPTION
**Pull request by metaspace**
Reported-by: Yura Sorokin <yura.sorokin@percona.com>
Signed-off-by: Andreas Hindborg <andreas.hindborg@wdc.com>

### CODE REVIEW

**Comment by metaspace** [comment]
Going to enable smoke tests for 1.0

**Review by yhr — CHANGES_REQUESTED** [review]
Looks good, but the commit message should say something about the constructor, not the destructor, right? :)

**Comment by metaspace** [comment]
> Looks good, but the commit message should say something about the constructor, not the destructor, right? :)

Depends. The use that caused problems was on an error path through the destructor. The fix is in the constructor though.

**Comment by yhr** [comment]
allright

**Review by yhr — APPROVED** [review]

**Pull request merged**
