### PR TITLE
docs: add corporate code of conduct

### PR DESCRIPTION
**Pull request by alandtse**

### CODE REVIEW

**Review by yhr — CHANGES_REQUESTED** [review]
Same comment as Damien's for the other projects: Please add a commit message. Also please add your Signed-off-by tag (git commit -s). Thanks!

**Comment by alandtse** [comment]
Took me a while to figure out the process. Thanks for the patience. Please let me know if I need to do anything else.

**Review by yhr — APPROVED** [review]
Looks good to me, thanks Alan!

**Comment by alandtse** [comment]
Thanks @yhr. Do you mind merging it in? Since this is adoption of the corporate policy, we wanted actual maintainers to merge it in instead of having me use my admin rights to do it.

**Pull request merged**
