### PR TITLE
util: Fix AddDirSeparatorAtEnd where back() can not be called on an e…

### PR DESCRIPTION
**Pull request by MaisenbacherD**
…mpty string

Fixes this issue: https://github.com/westerndigitalcorporation/zenfs/issues/227

Suggested-by: Yura Sorokin <yura.sorokin@percona.com>
Signed-off-by: Dennis Maisenbacher <dennis.maisenbacher@wdc.com>

### CODE REVIEW

**Comment by MaisenbacherD** [comment]
@percona-ysorokin This fix is slightly different from what you suggested. Does that work out for you? :)

**Review by percona-ysorokin — APPROVED** [review]
Looks good

**Comment by percona-ysorokin** [comment]
@MaisenbacherD could you also please make sure that we will have `v2.1.1` tag after this PR is merged.

**Comment by MaisenbacherD** [comment]
@percona-ysorokin Yes this will be tagged `v2.1.1` after the merge :)

**Review by yhr — APPROVED** [review]

**Pull request merged**
