### PR TITLE
Zenfs cmds

### PR DESCRIPTION
**Pull request by aravind-wdc**
Added 2 more commands to zenfs utility.
1. link - creates a hardlink
2. delete  - deletes specified file

These commands can be helpful for unit testing and debugging.
These are good to have features.

### CODE REVIEW

**Comment by MaisenbacherD** [comment]
The two commits that introduce the link and delete command to ZenFS utility look good to me.

We have now two pull requests for the LinkFile support commit (https://github.com/westerndigitalcorporation/zenfs/pull/156).

**Comment by yhr** [comment]
Let's review this after the link support has been merged. Also, please make sure to use the path-normalization function (zenfs_format_path) that was introduced with with backup/restore fixes

**Comment by aravind-wdc** [comment]
Rebased with master.

**Review by MaisenbacherD — APPROVED** [review]
Looks good to me!

**Comment by aravind-wdc** [comment]
Rebased on latest master.

**Review by metaspace — APPROVED** [review]
Looks good to me

**Review by yhr — APPROVED** [review]

**Pull request merged**
