### PR TITLE
util: add zbd micro bench tool

### PR DESCRIPTION
**Pull request by skyzh**
ZBD micro bench tool could help observe how a ZNS device performs when executing different ZBD commands. See README.md for usage information.

Signed-off-by: Alex Chi <iskyzh@gmail.com>

### CODE REVIEW

**Comment by yhr** [comment]
This is out of scope for this project - We have zbd support in fio tool already - see https://zonedstorage.io/benchmarking/fio/ .

**Review by yhr — COMMENTED** [review]
We use fio for benchmarking zbd devices, see the fio documentation.

**Comment by MatiasBjorling** [comment]
Hi Hans, 

Let's discuss. This tool is useful to validate potential overheads wrt to reset and finish. Which isn't easy to measure with fio at the moment.

**Comment by yhr** [comment]
Well, i don't disagree that might be useful :) a proper, configurable tool
would just do a better job.

AND I don't find any reason why a generic zbd benchmarking  tool should be
added to zenfs. If fio can't be extended, we can see if it would fit in
libzbd or as a separate project.

**Comment by yhr** [comment]
After discussing this with one of our fio developers, it seems feasible to add reset/finish measurements. Having this support in fio would enable a much broader range of different benchmarks. I'll close this if there are no more comments. Will reopen if we get pushback when upstreaming to fio.

**Comment by skyzh** [comment]
Looks good to me, and hope to use this functionality in fio in the future!

**Pull request closed without merging**
