### PR TITLE
zbd: Fix partial I/O handling in Append and DirectRead

### LINKED ISSUE #181: ZonedBlockDevice::DirectRead and Zone::Append don't handle partial I/O correctly
In Zone::Append, the pwrite should use left instead of size as the buffer size.
In ZonedBlockDevice::DirectRead, ret is incremented with the bytes read on every read, but the read is always for the full buffer at the same offset, so, e.g., two reads of the first half a buffer will be viewed as a successful read.

### PR DESCRIPTION
**Pull request by jsvaerke**
In Zone::Append, the pwrite is changed to use left instead of size as the buffer size.
In ZonedBlockDevice::DirectRead, logic has been changed to the same approach as in other
places in the code, where the number of bytes left is tracked and buffer pointers and
offsets are adjusted with the bytes already read.

Signed-off-by: Jorgen S. Hansen <jorgen.hansen@wdc.com>

Closes #181

### CODE REVIEW

**Comment by jsvaerke** [comment]
I'm not sure that the DirectRead part is covered by the smoke-test, and I'll be happy to run any additional tests.

**Review by MaisenbacherD — APPROVED** [review]
Nice catch! 
Looks good to me.

**Comment by yhr** [comment]
DirectRead is only called during migration, which is not tested by the current tests. I tested this branch on my garbage collection branch and it checked out.

**Review by yhr — APPROVED** [review]
Nice, thanks!

**Pull request merged**
